name: Deploy ke InfinityFree

on:
  push:
    branches:
      - main  # Ubah ke master jika branch utama Anda 'master'

jobs:
  web-deploy:
    name: Proses Deploy Terbuka
    runs-on: ubuntu-latest
    steps:
    - name: Ambil Code Terbaru
      uses: actions/checkout@v4

    - name: Upload via FTP Alternatif
      uses: SebastiaanBlondelle/ftp-deployment-action@v1.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: ./
        remote_dir: /htdocs/
        # Memaksa koneksi biasa karena InfinityFree sering menolak SSL/TLS otomatis
        security: 'loose' 
